from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.utils.html import escape


def _get_user_display_name(user):
    """
    Returns the most appropriate display name for the user.
    """

    full_name = (
        getattr(user, "get_full_name", lambda: "")()
        or ""
    ).strip()

    if full_name:
        return full_name

    username = (
        getattr(user, "username", "")
        or ""
    ).strip()

    if username:
        return username

    email = (
        getattr(user, "email", "")
        or ""
    ).strip()

    if email:
        return email.split("@")[0]

    return "there"


def _get_user_email(user):
    """
    Returns the user's registered email address.
    """

    return (
        getattr(user, "email", "")
        or ""
    ).strip()


def _get_notification_preferences(user):
    """
    Retrieves the user's email preferences.

    If preferences do not exist, they are created
    using the model's default values.
    """

    from .models import NotificationPreference

    preferences, _ = (
        NotificationPreference.objects.get_or_create(
            user=user
        )
    )

    return preferences


def _build_email_content(notification):
    """
    Creates the plain-text and HTML versions of
    a BudgetBuddy notification email.
    """

    user = notification.user

    name = _get_user_display_name(user)

    title = (
        getattr(notification, "title", "")
        or "BudgetBuddy Notification"
    ).strip()

    message = (
        getattr(notification, "message", "")
        or ""
    ).strip()

    notification_type = (
        getattr(
            notification,
            "notification_type",
            "System",
        )
        or "System"
    ).strip()

    # --------------------------------------------------------
    # Plain-text email
    # --------------------------------------------------------

    text_content = f"""
Hi {name},

{message}

Notification type: {notification_type}

This notification was generated by BudgetBuddy based on activity in your account.

Regards,
BudgetBuddy
Your personal finance companion
""".strip()

    # --------------------------------------------------------
    # HTML email
    # --------------------------------------------------------

    safe_name = escape(name)
    safe_title = escape(title)
    safe_message = escape(message).replace(
        "\n",
        "<br>",
    )
    safe_type = escape(notification_type)

    html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">

    <title>{safe_title}</title>
</head>

<body style="
    margin: 0;
    padding: 0;
    background-color: #f4f7f6;
    font-family: Arial, Helvetica, sans-serif;
">

    <table
        width="100%"
        cellpadding="0"
        cellspacing="0"
        border="0"
        style="background-color: #f4f7f6; padding: 32px 16px;"
    >
        <tr>
            <td align="center">

                <table
                    width="100%"
                    cellpadding="0"
                    cellspacing="0"
                    border="0"
                    style="
                        max-width: 600px;
                        background-color: #ffffff;
                        border-radius: 12px;
                        overflow: hidden;
                    "
                >

                    <!-- Header -->

                    <tr>
                        <td style="
                            padding: 28px 32px;
                            background-color: #111827;
                            color: #ffffff;
                        ">

                            <div style="
                                font-size: 22px;
                                font-weight: 700;
                                letter-spacing: -0.3px;
                            ">
                                BudgetBuddy
                            </div>

                            <div style="
                                margin-top: 6px;
                                font-size: 13px;
                                color: #a7f3d0;
                            ">
                                Your personal finance companion
                            </div>

                        </td>
                    </tr>


                    <!-- Content -->

                    <tr>
                        <td style="
                            padding: 32px;
                            color: #1f2937;
                        ">

                            <p style="
                                margin: 0 0 20px;
                                font-size: 16px;
                                line-height: 1.6;
                            ">
                                Hi {safe_name},
                            </p>

                            <h1 style="
                                margin: 0 0 18px;
                                font-size: 24px;
                                line-height: 1.3;
                                color: #111827;
                            ">
                                {safe_title}
                            </h1>

                            <div style="
                                padding: 20px;
                                background-color: #f0fdf4;
                                border-left: 4px solid #10b981;
                                border-radius: 6px;
                                font-size: 15px;
                                line-height: 1.7;
                                color: #374151;
                            ">
                                {safe_message}
                            </div>

                            <p style="
                                margin: 22px 0 0;
                                font-size: 12px;
                                color: #6b7280;
                            ">
                                Notification type:
                                <strong>{safe_type}</strong>
                            </p>

                        </td>
                    </tr>


                    <!-- Footer -->

                    <tr>
                        <td style="
                            padding: 22px 32px;
                            border-top: 1px solid #e5e7eb;
                            background-color: #fafafa;
                        ">

                            <p style="
                                margin: 0;
                                font-size: 12px;
                                line-height: 1.6;
                                color: #6b7280;
                            ">
                                This email was generated automatically
                                by BudgetBuddy based on activity in
                                your account.
                            </p>

                            <p style="
                                margin: 10px 0 0;
                                font-size: 12px;
                                color: #9ca3af;
                            ">
                                BudgetBuddy · Personal Finance Management
                            </p>

                        </td>
                    </tr>

                </table>

            </td>
        </tr>
    </table>

</body>
</html>
""".strip()

    return text_content, html_content


def send_notification_email(notification):
    """
    Sends a BudgetBuddy notification email.

    Returns:
        True  -> email sent
        False -> email skipped
    """

    user = notification.user

    recipient = _get_user_email(user)

    if not recipient:
        return False

    preferences = _get_notification_preferences(user)

    if not preferences.email_enabled:
        return False

    text_content, html_content = (
        _build_email_content(notification)
    )

    subject = (
        f"BudgetBuddy | "
        f"{notification.title}"
    )

    email = EmailMultiAlternatives(
        subject=subject,
        body=text_content,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=[recipient],
    )

    email.attach_alternative(
        html_content,
        "text/html",
    )

    email.send(
        fail_silently=False,
    )

    return True


def send_test_email(user):
    """
    Sends a professional test email to the
    authenticated user's registered email address.
    """

    recipient = _get_user_email(user)

    if not recipient:
        raise ValueError(
            "No email address is associated "
            "with this user."
        )

    name = _get_user_display_name(user)

    subject = "BudgetBuddy | Email notifications are ready"

    text_content = f"""
Hi {name},

Your BudgetBuddy email notification system is working correctly.

You will receive important financial updates at this email address when your notification preferences allow them.

You're all set.

Regards,
BudgetBuddy
Your personal finance companion
""".strip()

    safe_name = escape(name)

    html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">

    <title>BudgetBuddy Email Test</title>
</head>

<body style="
    margin: 0;
    padding: 0;
    background-color: #f4f7f6;
    font-family: Arial, Helvetica, sans-serif;
">

    <table
        width="100%"
        cellpadding="0"
        cellspacing="0"
        border="0"
        style="padding: 32px 16px;"
    >
        <tr>
            <td align="center">

                <table
                    width="100%"
                    cellpadding="0"
                    cellspacing="0"
                    border="0"
                    style="
                        max-width: 600px;
                        background-color: #ffffff;
                        border-radius: 12px;
                        overflow: hidden;
                    "
                >

                    <tr>
                        <td style="
                            padding: 30px 32px;
                            background-color: #111827;
                            color: #ffffff;
                        ">

                            <div style="
                                font-size: 22px;
                                font-weight: 700;
                            ">
                                BudgetBuddy
                            </div>

                            <div style="
                                margin-top: 6px;
                                font-size: 13px;
                                color: #a7f3d0;
                            ">
                                Email notification system
                            </div>

                        </td>
                    </tr>

                    <tr>
                        <td style="
                            padding: 32px;
                            color: #1f2937;
                        ">

                            <div style="
                                width: 44px;
                                height: 44px;
                                line-height: 44px;
                                text-align: center;
                                border-radius: 50%;
                                background-color: #dcfce7;
                                color: #15803d;
                                font-size: 22px;
                                margin-bottom: 20px;
                            ">
                                ✓
                            </div>

                            <h1 style="
                                margin: 0 0 14px;
                                font-size: 24px;
                                color: #111827;
                            ">
                                Email notifications are ready
                            </h1>

                            <p style="
                                margin: 0;
                                font-size: 15px;
                                line-height: 1.7;
                                color: #4b5563;
                            ">
                                Hi {safe_name}, your BudgetBuddy
                                email notification system is working
                                correctly.
                            </p>

                            <div style="
                                margin-top: 24px;
                                padding: 18px;
                                background-color: #f9fafb;
                                border-radius: 8px;
                                font-size: 14px;
                                line-height: 1.6;
                                color: #374151;
                            ">
                                Important financial updates will be
                                delivered to this email address according
                                to your notification preferences.
                            </div>

                        </td>
                    </tr>

                    <tr>
                        <td style="
                            padding: 22px 32px;
                            border-top: 1px solid #e5e7eb;
                            background-color: #fafafa;
                        ">

                            <p style="
                                margin: 0;
                                font-size: 12px;
                                color: #6b7280;
                            ">
                                BudgetBuddy · Personal Finance Management
                            </p>

                        </td>
                    </tr>

                </table>

            </td>
        </tr>
    </table>

</body>
</html>
""".strip()

    email = EmailMultiAlternatives(
        subject=subject,
        body=text_content,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=[recipient],
    )

    email.attach_alternative(
        html_content,
        "text/html",
    )

    email.send(
        fail_silently=False,
    )

    return True