# Generated by Django 6.0.7 on 2026-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Budget', 'Budget'), ('Budget Alert', 'Budget Alert'), ('Savings Goal', 'Savings Goal'), ('Reminder', 'Reminder'), ('System', 'System')], max_length=30),
        ),
    ]
